import { BiodataData } from '@/types/biodata';

export const sampleGroomData: BiodataData = {
  id: 'sample-groom-01',
  language: 'bn',
  template: 'classic',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  privacy: {
    isPublic: true,
    hidePhoto: false,
    hideContact: false,
    hideGuardianContact: false,
    hideCurrentAddress: false,
    isPasswordProtected: false,
    showWatermark: false,
    themeColor: '#b45309',
  },
  personal: {
    biodataType: 'male',
    fullName: 'মো: তানভীর আহমেদ',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    birthDate: '1997-04-15',
    age: '২৭ বছর',
    height: '৫ ফুট ৯ ইঞ্চি',
    complexion: 'উজ্জ্বল শ্যামলা',
    weight: '৬৮ কেজি',
    bloodGroup: 'B+',
    maritalStatus: 'unmarried',
    nationality: 'বাংলাদেশী (জন্মসূত্রে)',
    permanentDistrict: 'কুমিল্লা (চৌদ্দগ্রাম)',
    permanentAddress: 'গ্রাম: কাশীপুর, ডাকঘর: মিঞাবাজার, উপজেলা: চৌদ্দগ্রাম, জেলা: কুমিল্লা',
    presentDistrict: 'ঢাকা (মিরপুর-২)',
    presentAddress: 'বাড়ি # ১২, রোড # ৪, ব্লক # সি, মিরপুর-২, ঢাকা-১২১৬',
    specialAttributes: 'আলহামদুলিল্লাহ সম্পূর্ণ সুস্থ ও কোনো দীর্ঘমেয়াদী শারীরিক অসুস্থতা নেই।',
  },
  education: {
    educationType: 'both',
    highestDegree: 'বি.এস.সি ইন কম্পিউটার সায়েন্স & ইঞ্জিনিয়ারিং (CSE)',
    details: [
      {
        id: 'edu-1',
        degree: 'B.Sc. in CSE',
        institution: 'বুয়েট (BUET)',
        passingYear: '২০২০',
        result: 'CGPA ৩.৭৮ (৪.০০ এর মধ্যে)',
        groupOrMajor: 'কম্পিউটার সায়েন্স',
      },
      {
        id: 'edu-2',
        degree: 'এইচএসসি (বিজ্ঞান)',
        institution: 'নটর ডেম কলেজ, ঢাকা',
        passingYear: '২০১৫',
        result: 'GPA ৫.০০ (গোল্ডেন A+)',
        groupOrMajor: 'বিজ্ঞান বিভাগ',
      },
      {
        id: 'edu-3',
        degree: 'এসএসসি (বিজ্ঞান)',
        institution: 'কুমিল্লা জিলা স্কুল',
        passingYear: '২০১৩',
        result: 'GPA ৫.০০',
        groupOrMajor: 'বিজ্ঞান বিভাগ',
      },
    ],
    islamicEducation: 'শৈশবে হিফজুল কুরআন ৩ পারা ও তাজভীদ শিক্ষা সম্পন্ন। নিয়মিত তাফসীর ও হাদীসের দরস শুনে থাকি।',
    otherQualifications: 'AWS সার্টিফাইড ক্লাউড প্র্যাকটিশনার, ফুল-স্ট্যাক সফটওয়্যার আর্কিটেকচার।',
  },
  career: {
    occupation: 'সফটওয়্যার ইঞ্জিনিয়ার (Software Engineer)',
    designation: 'সিনিয়র সফটওয়্যার ইঞ্জিনিয়ার',
    organization: 'একটি শীর্ষস্থানীয় ফিনটেক বহুজাতিক প্রতিষ্ঠান (Dhaka & Remote)',
    workLocation: 'গুলশান-২, ঢাকা',
    monthlyIncome: '১,৪৫,০০০+ টাকা',
    careerDescription: 'গত ৪ বছর ধরে আধুনিক ফিনটেক ও পেমেন্ট গেটওয়ে সিস্টেমে সফটওয়্যার ডেভেলপমেন্ট করছি। ভবিষ্যৎ পরিকল্পনা দেশে ও বিদেশে হালাল টেকনোলজি উদ্যোগে অবদান রাখা।',
  },
  family: {
    fatherName: 'মো: আব্দুল কাদের',
    fatherOccupation: 'অবসরপ্রাপ্ত সরকারি কর্মকর্তা (শিক্ষা মন্ত্রণালয়)',
    fatherStatus: 'alive',
    motherName: 'নাসরিন আক্তার',
    motherOccupation: 'গৃহিণী',
    motherStatus: 'alive',
    totalBrothers: '২ জন (প্রার্থী সহ)',
    brothersDetails: 'ছোট ভাই ঢাকা বিশ্ববিদ্যালয়ে আন্তর্জাতিক সম্পর্ক বিভাগে মাস্টার্সে অধ্যয়নরত।',
    totalSisters: '১ জন',
    sistersDetails: 'বড় বোন বিবাহিতা, দুলাভাই একটি স্বনামধন্য ব্যাংকের অ্যাসিস্ট্যান্ট ভাইস প্রেসিডেন্ট (AVP)।',
    financialStatus: 'upper_middle',
    familyType: 'nuclear',
    familyBackgroundDescription: 'আমাদের পরিবার কুমিল্লা ও ঢাকায় অত্যন্ত সম্মানিত ও ধর্মপ্রাণ একটি মুসলিম পরিবার। ঢাকায় নিজস্ব ফ্ল্যাট ও গ্রামে পারিবারিক জমিজমা রয়েছে।',
    maternalUncleInfo: 'বড় মামা কাস্টমস কর্মকর্তা, মেঝ মামা ব্যবসায়ী (চট্টগ্রাম)।',
    paternalUncleInfo: 'চাচা স্থানীয় কলেজের অবসরপ্রাপ্ত অধ্যাপক।',
  },
  religion: {
    religion: 'ইসলাম (সুন্নি)',
    sectOrMazhab: 'আহলে সুন্নাত ওয়াল জামায়াত (হানাফী)',
    praysFiveTimes: 'regular',
    quranRecitation: 'yes',
    beardOrHijab: 'সুন্নতি দাড়ি রয়েছে এবং সর্বদা মার্জিত ও শালীন পোশাক পরিধান করি।',
    halalEarningCommitment: '১০০% হালাল উপার্জনে বিশ্বাসী, সুদ ও যেকোনো অনৈতিক আয় সম্পূর্ণ বর্জন করে চলি।',
    hobbiesAndInterests: 'বই পড়া (বিশেষ করে ইসলামী সাহিত্য ও প্রযুক্তি), ভ্রমণ এবং ব্যাডমিন্টন খেলা।',
    habitsAndLifestyle: 'ধূমপান সম্পূর্ণ মুক্ত, পরিচ্ছন্ন ও শান্ত স্বভাবের। পরিবার ও দ্বীনি জীবনকে সর্বোচ্চ অগ্রাধিকার দিই।',
  },
  expectations: {
    expectedAgeMin: '২১',
    expectedAgeMax: '২৫',
    expectedHeightMin: '৫ ফুট ১ ইঞ্চি',
    expectedComplexion: 'যেকোনো সুন্দর ও মার্জিত চেহারা',
    expectedEducation: 'কমপক্ষে স্নাতক (অধ্যয়নরত বা সম্পন্ন), দ্বীনি বিষয়ে সম্যক ধারণা।',
    expectedDistrict: 'ঢাকা, কুমিল্লা, নোয়াখালী, চাঁদপুর বা বৃহত্তর সিলেট (তবে ভালো পরিবার হলে যেকোনো জেলা বিবেচনাযোগ্য)',
    expectedProfession: 'গৃহিণী অথবা পর্দা রক্ষা করে শালীন কর্মসংস্থান/শিক্ষকতা।',
    expectedMaritalStatus: 'অবিবাহিত',
    religiousExpectations: 'নিয়মিত ৫ ওয়াক্ত নামাজী, পর্দাপুর্ণ ও দ্বীনদার পরিবারের কন্যা যিনি পরিবার ও দাম্পত্য জীবনে আন্তরিক হবেন।',
    generalExpectations: 'বিনয়ী, পরোপকারী ও হাসিখুশি স্বভাবের পাত্রী কাম্য। যৌতুক সম্পূর্ণ নিষিদ্ধ।',
  },
  contact: {
    candidatePhone: '01711-XXXXXX',
    candidateEmail: 'tanvir.eng@email.com',
    guardianName: 'মো: আব্দুল কাদের (পিতা)',
    guardianRelation: 'পিতা',
    guardianPhone: '01819-123456',
    alternativePhone: '01912-654321',
    contactTimePreference: 'প্রতিদিন মাগরিবের পর থেকে রাত ১০টা পর্যন্ত',
  },
};

export const sampleBrideData: BiodataData = {
  id: 'sample-bride-01',
  language: 'bn',
  template: 'royal',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  privacy: {
    isPublic: true,
    hidePhoto: false,
    hideContact: false,
    hideGuardianContact: false,
    hideCurrentAddress: false,
    isPasswordProtected: false,
    showWatermark: false,
    themeColor: '#9333ea',
  },
  personal: {
    biodataType: 'female',
    fullName: 'ফাতেমা তুজ জোহরা (মীম)',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    birthDate: '1999-09-20',
    age: '২৫ বছর',
    height: '৫ ফুট ৩ ইঞ্চি',
    complexion: 'উজ্জ্বল ফর্সা',
    weight: '৫২ কেজি',
    bloodGroup: 'O+',
    maritalStatus: 'unmarried',
    nationality: 'বাংলাদেশী (জন্মসূত্রে)',
    permanentDistrict: 'ময়মনসিংহ (ত্রিশাল)',
    permanentAddress: 'পৌরসভা রোড, ত্রিশাল, জেলা: ময়মনসিংহ',
    presentDistrict: 'ঢাকা (ধানমন্ডি)',
    presentAddress: 'বাড়ি # ৪৫, রোড # ৯/এ, ধানমন্ডি আ/এ, ঢাকা',
    specialAttributes: 'আলহামদুলিল্লাহ সম্পূর্ণ সুস্থ।',
  },
  education: {
    educationType: 'general',
    highestDegree: 'এম.বি.এ (মার্কেটিং) ও বি.বি.এ',
    details: [
      {
        id: 'edu-1',
        degree: 'MBA (Marketing)',
        institution: 'ঢাকা বিশ্ববিদ্যালয় (DU)',
        passingYear: '২০২৩',
        result: 'CGPA ৩.৬২',
        groupOrMajor: 'মার্কেটিং',
      },
      {
        id: 'edu-2',
        degree: 'BBA (Honours)',
        institution: 'ঢাকা বিশ্ববিদ্যালয় (DU)',
        passingYear: '২০২১',
        result: 'CGPA ৩.৬৫',
        groupOrMajor: 'ব্যবসায় শিক্ষা',
      },
      {
        id: 'edu-3',
        degree: 'এইচএসসি (ব্যবসায় শিক্ষা)',
        institution: 'ভিকারুননিসা নূন স্কুল অ্যান্ড কলেজ',
        passingYear: '২০১৭',
        result: 'GPA ৫.০০',
        groupOrMajor: 'ব্যবসায় শিক্ষা',
      },
    ],
    islamicEducation: 'ছোটবেলা থেকেই কুরআন তিলাওয়াত ও ইসলামিক বুনিয়াদি শিক্ষায় পারদর্শী। নিয়মিত পর্দা ও ইসলামিক রীতিনীতি মেনে চলি।',
    otherQualifications: 'গ্রাফিক ডিজাইন ও ডিজিটাল কন্টেন্ট তৈরিতে বিশেষ দক্ষতা ও শখ রয়েছে।',
  },
  career: {
    occupation: 'কন্টেন্ট স্ট্র্যাটেজিস্ট ও লেকচারার (পার্ট-টাইম)',
    designation: 'লেকচারার',
    organization: 'একটি বেসরকারি বিশ্ববিদ্যালয় ও ফ্রিল্যান্স কনসালটেন্সি',
    workLocation: 'ঢাকা',
    monthlyIncome: '৫০,০০০ - ৬০,০০০ টাকা',
    careerDescription: 'বর্তমানে শিক্ষকতা এবং ঘরে বসে রিমোট কনসালটেন্সি করছি। বিয়ের পর পারিবারিক দায়িত্বকে সর্বোচ্চ অগ্রাধিকার দিতে প্রস্তুত।',
  },
  family: {
    fatherName: 'প্রকৌশলী মাহমুদুল হাসান',
    fatherOccupation: 'নির্বাহী প্রকৌশলী (PWD - অবসরপ্রাপ্ত)',
    fatherStatus: 'alive',
    motherName: 'রাবেয়া সুলতানা',
    motherOccupation: 'সহকারী প্রধান শিক্ষিকা (সরকারি হাই স্কুল)',
    motherStatus: 'alive',
    totalBrothers: '১ জন',
    brothersDetails: 'মেকানিক্যাল ইঞ্জিনিয়ারিং পাস করে বর্তমানে জার্মানিতে পিএইচডি করছেন।',
    totalSisters: '১ জন (প্রার্থী নিজে)',
    sistersDetails: 'একমাত্র কন্যা।',
    financialStatus: 'upper_middle',
    familyType: 'nuclear',
    familyBackgroundDescription: 'উচ্চ শিক্ষিত ও মার্জিত রুচিসম্পন্ন পরিবার। ঢাকায় নিজস্ব বাড়ি রয়েছে।',
    maternalUncleInfo: 'মেজর (অবসরপ্রাপ্ত) বাংলাদেশ সেনাবাহিনী।',
    paternalUncleInfo: 'ব্যবসায়ী ও সিএ ফার্মের পার্টনার।',
  },
  religion: {
    religion: 'ইসলাম (সুন্নি)',
    sectOrMazhab: 'আহলে সুন্নাত ওয়াল জামায়াত',
    praysFiveTimes: 'regular',
    quranRecitation: 'yes',
    beardOrHijab: 'নিয়মিত হিজাব ও শালীন বোরকা পরিধান করি।',
    halalEarningCommitment: 'দ্বীন ও পারিবারিক শান্তির প্রতি শ্রদ্ধাশীল।',
    hobbiesAndInterests: 'রান্না করা, ক্যালিগ্রাফি আর্ট ও পরিবারের সাথে সময় কাটানো।',
    habitsAndLifestyle: 'শান্ত স্বভাব, পরোপকারী ও দায়িত্বশীল।',
  },
  expectations: {
    expectedAgeMin: '২৬',
    expectedAgeMax: '৩২',
    expectedHeightMin: '৫ ফুট ৭ ইঞ্চি',
    expectedComplexion: 'যেকোনো সুন্দর ব্যক্তিত্ব',
    expectedEducation: 'কমপক্ষে স্নাতক/ইঞ্জিনিয়ারিং/মেডিকেল/মাস্টার্স সম্পন্ন।',
    expectedDistrict: 'ঢাকা, ময়মনসিংহ, সিলেট বা অন্য যেকোনো জেলার মার্জিত পরিবার।',
    expectedProfession: 'ভালো প্রতিষ্ঠানে চাকরিজীবী (বিসিএস/ইঞ্জিনিয়ার/ব্যাংকার/ডাক্তার) বা প্রতিষ্ঠিত ব্যবসায়ী।',
    expectedMaritalStatus: 'অবিবাহিত',
    religiousExpectations: '৫ ওয়াক্ত নামাজী, সৎ, অমায়িক ও হালাল রোজগারে বিশ্বাসী দ্বীনদার পাত্র।',
    generalExpectations: 'পরিবার সচেতন, দায়িত্ববান ও পারস্পরিক বোঝাপড়ায় বিশ্বাসী পাত্র প্রত্যাশা করছি।',
  },
  contact: {
    candidatePhone: '',
    candidateEmail: '',
    guardianName: 'প্রকৌশলী মাহমুদুল হাসান (পিতা)',
    guardianRelation: 'পিতা',
    guardianPhone: '01712-987654',
    alternativePhone: '01815-321456',
    contactTimePreference: 'বিকেল ৫টার পর থেকে রাত ৯টা',
  },
};

export const sampleHinduGroomData: BiodataData = {
  id: 'sample-hindu-groom-01',
  language: 'bn',
  template: 'classic',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  privacy: {
    isPublic: true,
    hidePhoto: false,
    hideContact: false,
    hideGuardianContact: false,
    hideCurrentAddress: false,
    isPasswordProtected: false,
    showWatermark: false,
    themeColor: '#881337',
  },
  personal: {
    biodataType: 'male',
    fullName: 'প্রকৌশলী সুবীর চক্রবর্তী',
    photoUrl: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=400&auto=format&fit=crop&q=80',
    birthDate: '1996-08-20',
    age: '২৮ বছর',
    height: '৫ ফুট ৯ ইঞ্চি',
    complexion: 'উজ্জ্বল ফর্সা',
    weight: '৭০ কেজি',
    bloodGroup: 'O+',
    maritalStatus: 'unmarried',
    nationality: 'বাংলাদেশী (জন্মসূত্রে)',
    permanentDistrict: 'চট্টগ্রাম (রাউজান)',
    permanentAddress: 'গ্রাম: নোয়াপাড়া, উপজেলা: রাউজান, জেলা: চট্টগ্রাম',
    presentDistrict: 'ঢাকা (ধানমন্ডি)',
    presentAddress: 'রোড # ৭/এ, ধানমন্ডি আ/এ, ঢাকা-১২০৯',
    specialAttributes: 'সম্পূর্ণ সুস্থ ও কোনো শারীরিক অসুস্থতা নেই।',
  },
  education: {
    educationType: 'general',
    highestDegree: 'বি.এস.সি ইন ইলেকট্রিক্যাল & ইলেকট্রনিক ইঞ্জিনিয়ারিং (EEE)',
    details: [
      {
        id: 'hindu-edu-1',
        degree: 'B.Sc. in EEE',
        institution: 'চুয়েট (CUET)',
        passingYear: '২০১৯',
        result: 'CGPA ৩.৮২ (৪.০০ এর মধ্যে)',
        groupOrMajor: 'EEE',
      },
      {
        id: 'hindu-edu-2',
        degree: 'এইচএসসি (বিজ্ঞান)',
        institution: 'চট্টগ্রাম কলেজ',
        passingYear: '২০১৪',
        result: 'GPA ৫.০০ (গোল্ডেন A+)',
        groupOrMajor: 'বিজ্ঞান বিভাগ',
      },
      {
        id: 'hindu-edu-3',
        degree: 'এসএসসি (বিজ্ঞান)',
        institution: 'চট্টগ্রাম গভ. হাই স্কুল',
        passingYear: '২০১২',
        result: 'GPA ৫.০০',
        groupOrMajor: 'বিজ্ঞান বিভাগ',
      },
    ],
    otherQualifications: 'প্রজেক্ট ম্যানেজমেন্ট প্রফেশনাল (PMP) প্রশিক্ষণ সম্পন্ন।',
  },
  career: {
    occupation: 'সহকারী ব্যবস্থাপক (প্রকৌশল)',
    designation: 'অ্যাসিস্ট্যান্ট ম্যানেজার (সিস্টেম ইঞ্জিনিয়ারিং)',
    organization: 'একটি শীর্ষস্থানীয় বহুজাতিক টেলিকম প্রতিষ্ঠান (MNC)',
    workLocation: 'গুলশান, ঢাকা',
    monthlyIncome: '১,৩০,০০০+ টাকা',
    careerDescription: 'গত ৫ বছর ধরে টেলিকম নেটওয়ার্ক ও পাওয়ার সিস্টেমে পেশাগত দক্ষতা ও নিষ্ঠার সাথে কাজ করছি।',
  },
  family: {
    fatherName: 'প্রয়াত সন্তোষ চক্রবর্তী',
    fatherOccupation: 'অবসরপ্রাপ্ত ব্যাংক কর্মকর্তা (অগ্রণী ব্যাংক)',
    fatherStatus: 'deceased',
    motherName: 'মৌসুমী চক্রবর্তী',
    motherOccupation: 'গৃহিণী',
    motherStatus: 'alive',
    totalBrothers: '২ জন (প্রার্থী জ্যেষ্ঠ)',
    brothersDetails: 'ছোট ভাই বুয়েটে সিভিল ইঞ্জিনিয়ারিংয়ে শেষ বর্ষে অধ্যয়নরত।',
    totalSisters: '০',
    sistersDetails: '',
    financialStatus: 'upper_middle',
    familyType: 'nuclear',
    familyBackgroundDescription: 'চট্টগ্রামের ঐতিহ্যবাহী ও সম্ভ্রান্ত ব্রাহ্মণ পরিবার। ঢাকায় নিজস্ব অ্যাপার্টমেন্ট এবং চট্টগ্রামে পারিবারিক ভিটা রয়েছে।',
    maternalUncleInfo: 'বড় মামা অবসরপ্রাপ্ত সরকারি কলেজ অধ্যক্ষ, ছোট মামা ব্যবসায়ী।',
    paternalUncleInfo: 'জ্যাঠামশাই সুপ্রিম কোর্টের সিনিয়র আইনজীবী।',
  },
  religion: {
    religion: 'সনাতন (হিন্দু)',
    sectOrMazhab: 'স্মার্ত / শাক্ত ঐতিহ্য',
    gotra: 'শাণ্ডিল্য',
    caste: 'ব্রাহ্মণ (কায়স্থ বা সমমানের মার্জিত পাত্রী বিবেচ্য)',
    dietHabit: 'non_vegetarian',
    rashiNakshatra: 'তুলা রাশি / স্বাতী নক্ষত্র',
    pujaLifestyle: 'নিত্য সন্ধ্যাপ্রদীপ ও পারিবারিক পূজা-পার্বণ অত্যন্ত নিষ্ঠার সাথে পালন করি। ধর্মপরায়ণ, শান্ত ও পারিবারিক সংস্কৃতিপ্রেমী।',
    hobbiesAndInterests: 'বই পড়া, রবীন্দ্রসঙ্গীত শ্রবণ, বাগান করা ও পারিবারিক ভ্রমণ।',
    habitsAndLifestyle: 'ধূমপান ও মদ্যপানমুক্ত, সুস্থ জীবনাচরণ ও পারিবারিক মূল্যবোধে বিশ্বাসী।',
  },
  expectations: {
    expectedAgeMin: '২৩',
    expectedAgeMax: '২৭',
    expectedHeightMin: '৫ ফুট ২ ইঞ্চি',
    expectedComplexion: 'মার্জিত ও স্নিগ্ধ ব্যক্তিত্ব',
    expectedEducation: 'স্নাতক / মাস্টার্স / মেডিকেল / ইঞ্জিনিয়ারিং সম্পন্ন।',
    expectedDistrict: 'চট্টগ্রাম, ঢাকা, সিলেট বা যেকোনো এলাকার মার্জিত হিন্দু পরিবার।',
    expectedProfession: 'চাকরিজীবী বা পরিবারের কাজে আগ্রহী পাত্রী।',
    expectedMaritalStatus: 'অবিবাহিত',
    religiousExpectations: 'ধর্মীয় সংস্কার, ঐতিহ্য ও পারিবারিক সংস্কৃতির প্রতি শ্রদ্ধাশীল পাত্রী।',
    generalExpectations: 'অমায়িক স্বভাব, পারস্পরিক সম্মান ও পারিবারিক শান্তি রক্ষায় আগ্রহী জীবনসঙ্গিনী প্রত্যাশা করছি।',
  },
  contact: {
    candidatePhone: '01819-234567',
    candidateEmail: 'subir.chakraborty.cuet@gmail.com',
    guardianName: 'মৌসুমী চক্রবর্তী (মাতা)',
    guardianRelation: 'মাতা',
    guardianPhone: '01817-654321',
    alternativePhone: '01711-987654',
    contactTimePreference: 'সন্ধ্যা ৬টা থেকে রাত ১০টা',
  },
};

export const sampleElegantBrideData: BiodataData = {
  id: 'sample-elegant-bride-01',
  language: 'bn',
  template: 'elegant',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  privacy: {
    isPublic: true,
    hidePhoto: false,
    hideContact: false,
    hideGuardianContact: false,
    hideCurrentAddress: false,
    isPasswordProtected: false,
    showWatermark: false,
    themeColor: '#9f1239',
  },
  personal: {
    biodataType: 'female',
    fullName: 'অনন্যা রায় চৌধুরী',
    photoUrl: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=400&auto=format&fit=crop&q=80',
    birthDate: '1999-03-14',
    age: '২৫ বছর',
    height: '৫ ফুট ৪ ইঞ্চি',
    complexion: 'উজ্জ্বল ফর্সা',
    weight: '৫২ কেজি',
    bloodGroup: 'B+',
    maritalStatus: 'unmarried',
    nationality: 'বাংলাদেশী (জন্মসূত্রে)',
    permanentDistrict: 'ময়মনসিংহ (সদর)',
    permanentAddress: 'নয়াপাড়া, ময়মনসিংহ সদর, ময়মনসিংহ',
    presentDistrict: 'ঢাকা (উত্তরা)',
    presentAddress: 'সেক্টর # ৪, উত্তরা, ঢাকা-১২৩০',
    specialAttributes: 'সম্পূর্ণ সুস্থ ও স্বাভাবিক।',
  },
  education: {
    educationType: 'general',
    highestDegree: 'এম.বি.এ (মার্কেটিং) — ঢাকা বিশ্ববিদ্যালয়',
    details: [
      {
        id: 'hbride-edu-1',
        degree: 'MBA (Marketing)',
        institution: 'ঢাকা বিশ্ববিদ্যালয় (IBA/FBS)',
        passingYear: '২০২৩',
        result: 'CGPA ৩.৭৫',
        groupOrMajor: 'মার্কেটিং',
      },
      {
        id: 'hbride-edu-2',
        degree: 'BBA (Honors)',
        institution: 'ঢাকা বিশ্ববিদ্যালয়',
        passingYear: '২০২১',
        result: 'CGPA ৩.৭০',
        groupOrMajor: 'ব্যবসায় প্রশাসন',
      },
      {
        id: 'hbride-edu-3',
        degree: 'এইচএসসি (ব্যবসায় শিক্ষা)',
        institution: 'ভিকারুননিসা নূন স্কুল অ্যান্ড কলেজ',
        passingYear: '২০১৭',
        result: 'GPA ৫.০০',
        groupOrMajor: 'ব্যবসায় শিক্ষা',
      },
    ],
    otherQualifications: 'ডিজিটাল স্ট্র্যাটেজি ও বিজনেস অ্যানালিটিক্স কোর্স সম্পন্ন।',
  },
  career: {
    occupation: 'সিনিয়র এক্সিকিউটিভ (ব্র্যান্ড স্ট্র্যাটেজি)',
    designation: 'সিনিয়র এক্সিকিউটিভ',
    organization: 'একটি শীর্ষস্থানীয় বহুজাতিক এফএমসিজি (FMCG) প্রতিষ্ঠান',
    workLocation: 'বনানী, ঢাকা',
    monthlyIncome: '৬৫,০০০+ টাকা',
    careerDescription: 'বর্তমানে করপোরেট ব্র্যান্ড ম্যানেজমেন্টে কর্মরত। বিয়ের পর পারিবারিক সিদ্ধান্ত অনুযায়ী কর্মজীবন পরিচালনা করবেন।',
  },
  family: {
    fatherName: 'প্রদীপ কুমার রায় চৌধুরী',
    fatherOccupation: 'মহাব্যবস্থাপক (GM - একটি স্বনামধন্য শিল্প গ্রুপ)',
    fatherStatus: 'alive',
    motherName: 'অপর্ণা রায়',
    motherOccupation: 'কলেজ অধ্যাপিকা (অর্থনীতি বিভাগ)',
    motherStatus: 'alive',
    totalBrothers: '০',
    brothersDetails: '',
    totalSisters: '১ জন (প্রার্থী নিজে)',
    sistersDetails: 'একমাত্র সন্তান।',
    financialStatus: 'upper_middle',
    familyType: 'nuclear',
    familyBackgroundDescription: 'মার্জিত, উচ্চ শিক্ষিত ও সংস্কৃতিবান কায়স্থ পরিবার। ঢাকায় নিজস্ব ফ্ল্যাট রয়েছে।',
    maternalUncleInfo: 'মামা বিসিএস প্রশাসন ক্যাডার (যুগ্ম সচিব)।',
    paternalUncleInfo: 'চাচা প্রখ্যাত চিকিৎসক (কার্ডিওলজিস্ট)।',
  },
  religion: {
    religion: 'সনাতন (হিন্দু)',
    sectOrMazhab: 'স্মার্ত',
    gotra: 'কাশ্যপ',
    caste: 'কায়স্থ',
    dietHabit: 'non_vegetarian',
    rashiNakshatra: 'কুম্ভ রাশি',
    pujaLifestyle: 'ধার্মিক, নিয়মিত গীতা পাঠ ও গৃহপূজা সম্পাদন করেন। পারিবারিক সংস্কৃতির প্রতি শ্রদ্ধাশীল।',
    hobbiesAndInterests: 'সঙ্গীত (শাস্ত্রীয় সঙ্গীতের প্রশিক্ষণপ্রাপ্ত), সাহিত্য পাঠ ও ভ্রমণ।',
    habitsAndLifestyle: 'অমায়িক স্বভাব, ভদ্র, দায়িত্বশীল ও শান্ত স্বভাবের।',
  },
  expectations: {
    expectedAgeMin: '২৭',
    expectedAgeMax: '৩২',
    expectedHeightMin: '৫ ফুট ৮ ইঞ্চি',
    expectedComplexion: 'মার্জিত ব্যক্তিত্ব',
    expectedEducation: 'বুয়েট/আইবিএ/মেডিকেল/বিশ্ববিদ্যালয় থেকে স্নাতক/মাস্টার্স সম্পন্ন।',
    expectedDistrict: 'ঢাকা, ময়মনসিংহ, সিলেট, চট্টগ্রাম বা অন্য যেকোনো মার্জিত পরিবার।',
    expectedProfession: 'প্রতিষ্ঠিত করপোরেট প্রফেশনাল, প্রকৌশলী, বিসিএস ক্যাডার বা ব্যাংকার।',
    expectedMaritalStatus: 'অবিবাহিত',
    religiousExpectations: 'সনাতন সংস্কৃতির প্রতি শ্রদ্ধাশীল ও ধার্মিক পাত্র।',
    generalExpectations: 'সৎ, রুচিশীল ও দায়িত্ববান পাত্র প্রত্যাশা করছি।',
  },
  contact: {
    candidatePhone: '',
    candidateEmail: '',
    guardianName: 'প্রদীপ কুমার রায় চৌধুরী (পিতা)',
    guardianRelation: 'পিতা',
    guardianPhone: '01715-876543',
    alternativePhone: '01819-123456',
    contactTimePreference: 'সন্ধ্যা ৭টা থেকে রাত ১০টা',
  },
};

export const sampleEnglishProfileData: BiodataData = {
  id: 'sample-english-groom-01',
  language: 'en',
  template: 'elegant',
  createdAt: new Date().toISOString(),
  updatedAt: new Date().toISOString(),
  privacy: {
    isPublic: true,
    hidePhoto: false,
    hideContact: false,
    hideGuardianContact: false,
    hideCurrentAddress: false,
    isPasswordProtected: false,
    showWatermark: false,
    themeColor: '#e11d48',
  },
  personal: {
    biodataType: 'male',
    fullName: 'Farhan Chowdhury',
    photoUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&auto=format&fit=crop&q=80',
    birthDate: '1996-05-18',
    age: '28 Years',
    height: "5' 11\"",
    complexion: 'Fair',
    weight: '72 kg',
    bloodGroup: 'O+',
    maritalStatus: 'unmarried',
    nationality: 'Bangladeshi (By Birth)',
    permanentDistrict: 'Sylhet',
    permanentAddress: 'Chowdhury Bari, Subidbazar, Sylhet',
    presentDistrict: 'Dhaka (Gulshan-2)',
    presentAddress: 'Road # 55, Gulshan-2, Dhaka-1212',
    specialAttributes: 'Non-smoker, physically active and completely healthy.',
  },
  education: {
    educationType: 'general',
    highestDegree: 'B.Sc. in Computer Science & Engineering',
    details: [
      {
        id: 'eng-edu-1',
        degree: 'B.Sc. in CSE',
        institution: 'BUET',
        passingYear: '2019',
        result: 'CGPA 3.82 / 4.00',
        groupOrMajor: 'Computer Science',
      },
      {
        id: 'eng-edu-2',
        degree: 'HSC (Science)',
        institution: 'Notre Dame College, Dhaka',
        passingYear: '2014',
        result: 'GPA 5.00',
        groupOrMajor: 'Science',
      },
    ],
    otherQualifications: 'AWS Certified Solutions Architect & Engineering Team Lead.',
  },
  career: {
    occupation: 'Software Engineer',
    designation: 'Lead Software Engineer',
    organization: 'FinTech Multinational, Dhaka & Singapore',
    monthlyIncome: '2,50,000+ BDT',
    workLocation: 'Gulshan-2, Dhaka',
    careerDescription: 'Scaling enterprise cloud solutions and technology entrepreneurship.',
  },
  family: {
    fatherName: 'Engr. Mahmudul Chowdhury',
    fatherStatus: 'deceased',
    fatherOccupation: 'Former Chief Engineer',
    motherName: 'Syeda Rehana Begum',
    motherStatus: 'alive',
    motherOccupation: 'Homemaker',
    totalBrothers: '1',
    brothersDetails: 'Elder brother is a Senior Data Scientist in Canada.',
    totalSisters: '1',
    sistersDetails: 'Younger sister is studying Architecture at BUET.',
    financialStatus: 'upper_middle',
    familyType: 'nuclear',
    familyBackgroundDescription: 'Upper Middle Class, respected and educated family background.',
  },
  religion: {
    religion: 'Islam',
    praysFiveTimes: 'regular',
    dietHabit: 'non_vegetarian',
    hobbiesAndInterests: 'Tech innovation, reading books, travel.',
    habitsAndLifestyle: 'Practicing, moderate, respectful of personal space and family values.',
  },
  expectations: {
    expectedAgeMin: '23',
    expectedAgeMax: '27',
    expectedHeightMin: "5' 3\"",
    expectedDistrict: 'Dhaka, Sylhet, Chittagong or any respectful family',
    generalExpectations: 'Looking for an educated, kind-hearted partner who values mutual respect, open communication and family harmony.',
  },
  contact: {
    candidatePhone: '',
    candidateEmail: 'farhan.chowdhury.dev@gmail.com',
    guardianName: 'Syeda Rehana Begum (Mother)',
    guardianRelation: 'Mother',
    guardianPhone: '01712-345678',
    alternativePhone: '01819-876543',
    contactTimePreference: 'Evenings (6:00 PM - 9:30 PM)',
  },
};

export const sampleHinduBrideData: BiodataData = sampleElegantBrideData;


